baseURL = 'https://www.afcroza.com/'
languageCode = 'en-us'
title = 'AFC Roza'
theme = "TatBanTheme2.0"
disqusShortname = 'afcroza'
enableGitInfo = true



[taxonomies]
  category = 'categories'
  tag = 'tags'




[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true # Allow HTML in md files

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Our Journey"
    url = "/journey/"
    weight = 2
  [[menu.main]]
    name = "Squad"
    url = "/squad/"
    weight = 3
  [[menu.main]]
    name = "League Table"
    url = "/table/"
    weight = 4
  [[menu.main]]
    name = "Fixtures & Results"
    url = "/fixtures/"
    weight = 5
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 6
  [[menu.main]]
    name = "Sponsors"
    url = "/sponsors/"
    weight = 7
  [[menu.main]]
    name = "Shop"
    url = "/shop/"
    weight = 8
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 9

    
[module]
  [module.hugoVersion]
    extended = true
    min = "0.60.0"
    max = "0.97.0"