---  # yamllint disable-line rule:new-lines
name: Weekly Data Scraping

on:
  schedule:
    - cron: '0 14 * * 1'  # Run every Monday at 2pm

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Fixture Scraping Script
        run: python fixturesscrapeupdate.py

      - name: Run Results Scraping Script
        run: python resultsscrapingscript.py

    -   name: Run Scraping of Table
        run: python scrapetable.py
