name: Weekly Data Scraping
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 14 * * *' # every day at 8 am

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Install Python Dependencies
      run: pip install -r requirements.txt

    - name: Scrape Files
      run: |
        python scripts/fixturescrapeupdate.py
        python scripts/resultsscrapeupdate.py
        python scripts/scrapetable.py

    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you