<<<<<<< HEAD
# This workflow executes several linters on changed files based on languages used in your code base whenever 
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base
=======
name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
>>>>>>> 3d054ba1992e61ecf986397494f4f0e1b08f3237

trigger: none

parameters:
  - name: PythonVersion
    type: string
    values:
      - 3.9
      - 3.10
      - 3.11
    default: 3.11

pool:
  vmImage: windows-latest

steps:
  - checkout: self

  - task: UsePythonVersion@0
    displayName: 'Use Python ${{ parameters.PythonVersion }}'
    inputs:
      versionSpec: ${{ parameters.PythonVersion }}

  - script: |
      pip install -r requirements.txt
      pytest --junitxml=TEST-shiftleft.xml
    workingDirectory: tests/ci
    displayName: 'Run the CI Tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TEST-*.xml'
    inputs:
      searchFolder: tests/ci
      failTaskOnFailedTests: true
    condition: always()
